### ISSUE TITLE
using default kubeadmin (kube:admin) does not appear to work

### ISSUE THREAD

**Issue by rayashworth** [open-cluster-management/cluster-keeper#26]
Trying to test using kubeadmin token.

Creating context ck
Creating ServiceAccount kube:admin
Error from server (NotFound): serviceaccounts "kube:admin" not found
Logging in as ServiceAccount kube:admin
error: The token provided is invalid or expired.

**Comment by KevinFCormier** [comment]
Duplicate of #27
